-- Development seed data
-- Run after migrations: supabase db reset

-- Note: auth.users rows must be created via Supabase Auth API.
-- This seed assumes two test users have been created and their UUIDs are known.
-- Replace these UUIDs with those generated by `supabase start` or the dashboard.

-- Example household (uncomment and replace UUIDs to use):

-- INSERT INTO public.households (id, name, created_by) VALUES
--   ('00000000-0000-0000-0000-000000000001', 'Casa García', '<user-uuid>');
