// Auto-generated by: supabase gen types typescript --local
// Re-generate after schema changes to keep this file in sync.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type IngredientCategory = 'proteina' | 'carbohidrato' | 'verdura'

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id:         string
          email:      string
          full_name:  string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id:          string
          email:       string
          full_name?:  string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?:         string
          email?:      string
          full_name?:  string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'users_id_fkey'
            columns: ['id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      households: {
        Row: {
          id:         string
          name:       string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?:         string
          name:        string
          created_by:  string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?:         string
          name?:       string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      household_members: {
        Row: {
          id:           string
          household_id: string
          user_id:      string
          role:         Database['public']['Enums']['household_role']
          joined_at:    string
        }
        Insert: {
          id?:           string
          household_id:  string
          user_id:       string
          role?:         Database['public']['Enums']['household_role']
          joined_at?:    string
        }
        Update: {
          id?:           string
          household_id?: string
          user_id?:      string
          role?:         Database['public']['Enums']['household_role']
          joined_at?:    string
        }
        Relationships: []
      }
      family_profiles: {
        Row: {
          id:         string
          user_id:    string
          name:       string
          created_at: string
        }
        Insert: {
          id?:         string
          user_id:     string
          name:        string
          created_at?: string
        }
        Update: {
          id?:         string
          user_id?:    string
          name?:       string
          created_at?: string
        }
        Relationships: []
      }
      ingredients: {
        Row: {
          id:         string
          user_id:    string
          name:       string
          category:   IngredientCategory
          created_at: string
        }
        Insert: {
          id?:         string
          user_id:     string
          name:        string
          category:    IngredientCategory
          created_at?: string
        }
        Update: {
          id?:         string
          user_id?:    string
          name?:       string
          category?:   IngredientCategory
          created_at?: string
        }
        Relationships: []
      }
      shopping_items: {
        Row: {
          id:         string
          user_id:    string
          name:       string
          category:   IngredientCategory
          checked:    boolean
          created_at: string
        }
        Insert: {
          id?:         string
          user_id:     string
          name:        string
          category:    IngredientCategory
          checked?:    boolean
          created_at?: string
        }
        Update: {
          id?:         string
          user_id?:    string
          name?:       string
          category?:   IngredientCategory
          checked?:    boolean
          created_at?: string
        }
        Relationships: []
      }
      recipes: {
        Row: {
          id:              string
          user_id:         string
          name:            string
          cooked_for_id:   string | null
          cooked_for_name: string
          proteins_g:      number
          carbs_g:         number
          vegetables_g:    number
          cooked_at:       string
          created_at:      string
        }
        Insert: {
          id?:              string
          user_id:          string
          name:             string
          cooked_for_id?:   string | null
          cooked_for_name?: string
          proteins_g?:      number
          carbs_g?:         number
          vegetables_g?:    number
          cooked_at?:       string
          created_at?:      string
        }
        Update: {
          id?:              string
          user_id?:         string
          name?:            string
          cooked_for_id?:   string | null
          cooked_for_name?: string
          proteins_g?:      number
          carbs_g?:         number
          vegetables_g?:    number
          cooked_at?:       string
          created_at?:      string
        }
        Relationships: []
      }
    }
    Views:     Record<string, never>
    Functions: Record<string, never>
    Enums: {
      household_role: 'admin' | 'member'
    }
    CompositeTypes: Record<string, never>
  }
}
